package layout

import com.example.mad_ind05_lastname_nithin.R

object StateDataModel {
        val stateList = listOf<States>(
            States("Alabama", "Yellowhammer State", "50,744 Sq. Miles", R.drawable.alabama,R.drawable.a),
            States("Alaska", "The Last Frontier", "571,951 Sq. Miles", R.drawable.alaska,R.drawable.b),
            States("Arizona", "The Grand Canyon State", "113,635 Sq. Miles", R.drawable.arizona,R.drawable.c),
            States("Arkansas", "The Natural State", "52,068 Sq. Miles", R.drawable.arkansas,R.drawable.d),
            States("California", "The Golden State", "155,959 Sq. Miles", R.drawable.california,R.drawable.e),
            States("Colorado", "The Centennial State", "103,718 Sq. Miles", R.drawable.coloroda,R.drawable.f),
            States("Connecticut", "The Constitution State", "4,845 Sq. Miles", R.drawable.connecticut,R.drawable.g),
            States("Delaware", "The First State", "1,954 Sq. Miles", R.drawable.delaware,R.drawable.h),
            States("Florida", "The Sunshine State", "53,927 Sq. Miles", R.drawable.florida,R.drawable.i),
            States("Georgia", "The Peach State", "57,906 Sq. Miles", R.drawable.georgia,R.drawable.j),
            States("Hawaii", "The Aloha State", "6,423 Sq. Miles", R.drawable.hawaii,R.drawable.k),
            States("Idaho", "The Gem State", "82,747 Sq. Miles", R.drawable.idaho,R.drawable.l),
            States("Illinois", "Prairie State", "55,584 Sq. Miles", R.drawable.illionois,R.drawable.m),
            States("Indiana", "The Hoosier State", "35,867 Sq. Miles", R.drawable.indiana,R.drawable.n),
            States("Iowa", "The Hawkeye State", "55,869 Sq. Miles", R.drawable.iowa,R.drawable.o),
            States("Kansas", "The Sunflower State", "81,815 Sq. Miles", R.drawable.kansas,R.drawable.p),
            States("Kentucky", "The Bluegrass State", "39,728 Sq. Miles", R.drawable.kentucky,R.drawable.q),
            States("Louisiana", "The Pelican State", "43,562 Sq. Miles", R.drawable.louisiana,R.drawable.r),
            States("Maine", "The Pine Tree State", "30,862 Sq. Miles", R.drawable.maine,R.drawable.s),
            States("Maryland", "The Old Line State", "9,774 Sq. Miles", R.drawable.maryland,R.drawable.t),
            States("Massachusetts", "The Bay State", "7,840 Sq. Miles", R.drawable.massachusetts,R.drawable.u),
            States("Michigan", "The Great Lakes State", "56,804 Sq. Miles", R.drawable.michigan,R.drawable.v),
            States("Minnesota", "The North Star State", "79,610 Sq. Miles", R.drawable.minnesota,R.drawable.w),
            States("Mississippi", "The Magnolia State", "46,907 Sq. Miles", R.drawable.mississippi,R.drawable.x),
            States("Missouri", "The Show Me State", "68,886 Sq. Miles", R.drawable.missouri,R.drawable.y),
            States("Montana", "The Treasure State", "145,552 Sq. Miles", R.drawable.montana,R.drawable.z),
            States("Nebraska", "The Cornhusker State", "76,872 Sq. Miles", R.drawable.nebraska,R.drawable.ab),
            States("Nevada", "The Silver State", "109,826 Sq. Miles", R.drawable.nevada,R.drawable.ac),
            States("New Hampshire", "The Granite State", "8,968 Sq. Miles", R.drawable.newhampshire,R.drawable.ad),
            States("New Jersey", "The Garden State", "7,417 Sq. Miles", R.drawable.newjersey,R.drawable.ae),
            States("New Mexico", "The Land of Enchantment", "121,356 Sq. Miles", R.drawable.newmexico,R.drawable.af),
            States("New York", "The Empire State", "47,214 Sq. Miles", R.drawable.newyork,R.drawable.ag),
            States("North Carolina", "The Tar Heel State", "48,711 Sq. Miles", R.drawable.northcarolina,R.drawable.ah),
            States("North Dakota", "The Peace Garden State", "68,976 Sq. Miles", R.drawable.northdakota,R.drawable.ai),
            States("Ohio", "The Buckeye State", "40,948 Sq. Miles", R.drawable.ohio,R.drawable.aj),
            States("Oklahoma", "The Sooner State", "68,667 Sq. Miles", R.drawable.oklahoma,R.drawable.ak),
            States("Oregon", "The Beaver State", "95,997 Sq. Miles", R.drawable.oregon,R.drawable.al),
            States("Pennsylvania", "The Keystone State", "44,817 Sq. Miles", R.drawable.pennsylvania,R.drawable.am),
            States("Rhode Island", "The Ocean State", "1,045 Sq. Miles", R.drawable.rhodeisland,R.drawable.an),
            States("South Carolina", "The Palmetto State", "30,109 Sq. Miles", R.drawable.southcarolina,R.drawable.ao),
            States("South Dakota", "Mount Rushmore State", "75,885 Sq. Miles", R.drawable.southdakota,R.drawable.ap),
            States("Tennessee", "The Volunteer State", "41,217 Sq. Miles", R.drawable.tennessee,R.drawable.aq),
            States("Texas", "The Lone Star State", "261,797 Sq. Miles", R.drawable.texas,R.drawable.ar),
            States("Utah", "The Beehive State", "82,144 Sq. Miles", R.drawable.utah,R.drawable.az),
            States("Vermont", "The Green Mountain State", "9,250 Sq. Miles", R.drawable.vermont,R.drawable.at),
            States("Virginia", "The Old Dominion State", "39,594 Sq. Miles", R.drawable.virginia,R.drawable.au),
            States("Washington", "The Evergreen State", "66,544 Sq. Miles", R.drawable.washington,R.drawable.av),
            States("West Virginia", "The Mountain State", "24,078 Sq. Miles", R.drawable.westvirginia,R.drawable.aw),
            States("Wisconsin", "The Badger State", "54,310 Sq. Miles", R.drawable.wisconsin,R.drawable.ax),
            States("Wyoming", "The Equality or Cowboy State", "97,100 Sq. Miles", R.drawable.wyoming,R.drawable.ay)

        )
    }